name: Backend CI

on:
  push:
    branches: [main]
    paths-ignore:
    - "ahoy_frontend/**"
  pull_request:
    branches: [main]
    paths-ignore:
    - "ahoy_frontend/**"
  
defaults:
  run:
    working-directory: backend
  
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.9.7
          uses: action/setup-python@v2
          with:
            python-version: 3.9.7

    
