name: Backend CI

on:
  push:
    branches: [main]
    paths-ignore:
    - "ahoy_frontend/**"
  pull_request:
    branches: [main]
    paths-ignore:
    - "ahoy_frontend/**"
  
defaults:
  run:
    working-directory: ahoy_backend
  
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: Display python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Mypy
        run: mypy .

    
