name: Backend CI

on:
  push:
    branches: [main]
    paths-ignore:
    - "ahoy_frontend/**"
  pull_request:
    branches: [main]
    paths-ignore:
    - "ahoy_frontend/**"
  
defaults:
  run:
    working-directory: ahoy_backend
  
env:
  DJANGO_SETTINGS_MODULE: ahoy_backend.settings
  DJANGO_SECRET_KEY: lol
  PYTHON_VERSION: 3.9.7

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install dependencies from requirements.txt
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run mypy
        run: mypy .

  prospector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install dependencies from requirements.txt
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run prospector
        run: prospector --uses django -X

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install dependencies from requirements.txt
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest

    
