name: Backend CI

on:
  push:
    branches: [main]
    paths-ignore:
    - "ahoy_frontend/**"
  pull_request:
    branches: [main]
    paths-ignore:
    - "ahoy_frontend/**"
  
defaults:
  run:
    working-directory: ahoy_backend
  
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: Install dependencies from requirements.txt
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
  mypy:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - run: pwd
      - run: ls
      - run: mypy .
      

    
